import { SupportedLanguage } from '../types/localization';

const LOCALE_STORAGE_KEY = 'tasker_app_language';

const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    app_name: 'TASKER',
    dashboard: 'Dashboard',
    pending_tasks: 'Pending Tasks',
    all_tasks: 'All Tasks',
    completed_tasks: 'Completed',
    bin: 'Bin',
    settings: 'Settings',
    workspaces: 'Workspaces',
    personal: 'Personal',
    family: 'Family & Home',
    business: 'Business',
    finance: 'Finance & Bills',
    vehicles: 'Vehicles & PUC',
    documents: 'Documents & Vault',
    templates: 'Checklists',
    reports: 'Reports',
    ask_ai: 'Ask AI',
    add_task: 'Add Task',
    search_placeholder: 'Search tasks, bills, docs, people...',
    streak_label: 'Day Streak',
    high_priority: 'Urgent',
    due_today: 'Due Today',
    overdue: 'Overdue',
    pay_now: 'Pay via UPI',
    voice_input: 'Speak to add task',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
  },
  hi: {
    app_name: 'टास्कर',
    dashboard: 'डैशबोर्ड',
    pending_tasks: 'बाकी कार्य',
    all_tasks: 'सभी कार्य',
    completed_tasks: 'पूर्ण कार्य',
    bin: 'कचरा पेटी',
    settings: 'सेटिंग्स',
    workspaces: 'कार्यक्षेत्र',
    personal: 'व्यक्तिगत',
    family: 'परिवार और घर',
    business: 'व्यवसाय',
    finance: 'वित्त और बिल',
    vehicles: 'वाहन और पीयूसी',
    documents: 'दस्तावेज और वॉल्ट',
    templates: 'चेकलिस्ट',
    reports: 'रिपोर्ट',
    ask_ai: 'एआई से पूछें',
    add_task: 'कार्य जोड़ें',
    search_placeholder: 'कार्य, बिल, दस्तावेज खोजें...',
    streak_label: 'दिन की स्ट्रीक',
    high_priority: 'अति आवश्यक',
    due_today: 'आज देय',
    overdue: 'अतिदेय',
    pay_now: 'यूपीआई से भुगतान करें',
    voice_input: 'बोलकर कार्य जोड़ें',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
  },
  mr: {
    app_name: 'टास्कर',
    dashboard: 'डॅशबोर्ड',
    pending_tasks: 'प्रलंबित कामे',
    all_tasks: 'सर्व कामे',
    completed_tasks: 'पूर्ण झालेली',
    bin: 'कचरा पेटी',
    settings: 'सेटिंग्ज',
    workspaces: 'कार्यक्षेत्र',
    personal: 'वैयक्तिक',
    family: 'कुटुंब आणि घर',
    business: 'व्यवसाय',
    finance: 'आर्थिक आणि बिले',
    vehicles: 'वाहने आणि पीयूसी',
    documents: 'कागदपत्रे आणि वॉल्ट',
    templates: 'चेकलिस्ट',
    reports: 'अहवाल',
    ask_ai: 'एआय विचारा',
    add_task: 'नवीन काम जोडा',
    search_placeholder: 'कामे, बिले, कागदपत्रे शोधा...',
    streak_label: 'दिवसांची मालिका',
    high_priority: 'तातडीचे',
    due_today: 'आज देय',
    overdue: 'मुदत संपली',
    pay_now: 'यूपीआय द्वारे भरा',
    voice_input: 'बोलून काम जोडा',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    delete: 'हटवा',
    edit: 'बदला',
  },
  ta: {
    app_name: 'டாஸ்கர்',
    dashboard: 'டாஷ்போர்டு',
    pending_tasks: 'நிலுவை பணிகள்',
    all_tasks: 'அனைத்து பணிகள்',
    completed_tasks: 'முடிந்த பணிகள்',
    bin: 'குப்பைத் தொட்டி',
    settings: 'அமைப்புகள்',
    workspaces: 'பணிப்பிடங்கள்',
    personal: 'தனிப்பட்ட',
    family: 'குடும்பம் & வீடு',
    business: 'வணிகம்',
    finance: 'நிதி & பில்கள்',
    vehicles: 'வாகனங்கள் & PUC',
    documents: 'ஆவணங்கள்',
    templates: 'வார்ப்புருக்கள்',
    reports: 'அறிக்கைகள்',
    ask_ai: 'AI உதவி',
    add_task: 'பணி சேர்',
    search_placeholder: 'பணிகள், பில்கள் தேடுக...',
    streak_label: 'தொடர் நாட்கள்',
    high_priority: 'அவசரம்',
    due_today: 'இன்று முடிவடைகிறது',
    overdue: 'காலாவதியானது',
    pay_now: 'UPI மூலம் செலுத்துங்கள்',
    voice_input: 'பேசி பணி சேர்க்கவும்',
    save: 'சேமி',
    cancel: 'ரத்து செய்',
    delete: 'நீக்கு',
    edit: 'திருத்து',
  },
  te: {
    app_name: 'టాస్కర్',
    dashboard: 'డ్యాష్‌బోర్డ్',
    pending_tasks: 'పెండింగ్ పనులు',
    all_tasks: 'అన్ని పనులు',
    completed_tasks: 'పూర్తయినవి',
    bin: 'ట్రాష్ బిన్',
    settings: 'సెట్టింగ్‌లు',
    workspaces: 'వర్క్‌స్పేస్‌లు',
    personal: 'వ్యక్తిగత',
    family: 'కుటుంబం & ఇల్లు',
    business: 'వ్యాపారం',
    finance: 'ఆర్థిక & బిల్లులు',
    vehicles: 'వాహనాలు & PUC',
    documents: 'పత్రాలు',
    templates: 'టెంప్లేట్లు',
    reports: 'నివేదికలు',
    ask_ai: 'AI ని అడగండి',
    add_task: 'పని జోడించండి',
    search_placeholder: 'పనులు, బిల్లులు వెతకండి...',
    streak_label: 'రోజుల స్ట్రీక్',
    high_priority: 'అత్యవసరం',
    due_today: 'ఈ రోజు గడువు',
    overdue: 'గడువు ముగిసింది',
    pay_now: 'UPI ద్వారా చెల్లించండి',
    voice_input: 'మాట్లాడి పనిని జోడించండి',
    save: 'సేవ్ చేయండి',
    cancel: 'రద్దు చేయండి',
    delete: 'తొలగించండి',
    edit: 'సవరించండి',
  },
  bn: {
    app_name: 'টাস্কার',
    dashboard: 'ড্যাশবোর্ড',
    pending_tasks: 'বকেয়া কাজ',
    all_tasks: 'সমস্ত কাজ',
    completed_tasks: 'সম্পন্ন কাজ',
    bin: 'রিসাইকেল বিন',
    settings: 'সেটিংস',
    workspaces: 'ওয়ার্কস্পেস',
    personal: 'ব্যক্তিগত',
    family: 'পরিবার ও বাড়ি',
    business: 'ব্যবসা',
    finance: 'অর্থ ও বিল',
    vehicles: 'যানবাহন ও পিইউসি',
    documents: 'নথিপত্র ও ভল্ট',
    templates: 'চেকলিস্ট',
    reports: 'প্রতিবেদন',
    ask_ai: 'AI-কে জিজ্ঞাসা করুন',
    add_task: 'কাজ যোগ করুন',
    search_placeholder: 'কাজ, বিল, নথি খুঁজুন...',
    streak_label: 'দিনের ধারাবাহিকতা',
    high_priority: 'জরুরী',
    due_today: 'আজকের শেষ তারিখ',
    overdue: 'মেয়াদোত্তীর্ণ',
    pay_now: 'UPI মাধ্যমে দিন',
    voice_input: 'মুখে বলে কাজ যোগ করুন',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    delete: 'মুছুন',
    edit: 'সম্পাদনা',
  },
  gu: {
    app_name: 'ટાસ્કર',
    dashboard: 'ડેશબોર્ડ',
    pending_tasks: 'બાકી કામો',
    all_tasks: 'બધા કામો',
    completed_tasks: 'પૂર્ણ થયેલ',
    bin: 'કચરાપેટી',
    settings: 'સેટિંગ્સ',
    workspaces: 'વર્કસ્પેસ',
    personal: 'અંગત',
    family: 'પરિવાર અને ઘર',
    business: 'વેપાર',
    finance: 'નાણાં અને બિલ',
    vehicles: 'વાહનો અને પીયુસી',
    documents: 'દસ્તાવેજો',
    templates: 'ચેકલિસ્ટ',
    reports: 'અહેવાલો',
    ask_ai: 'AI પૂછો',
    add_task: 'કામ ઉમેરો',
    search_placeholder: 'કામો, બિલો શોધો...',
    streak_label: 'દિવસોનો સિલસિલો',
    high_priority: 'તાત્કાલિક',
    due_today: 'આજે પૂર્ણ કરવાનું',
    overdue: 'મુદત વીતી ગઈ',
    pay_now: 'UPI દ્વારા ચૂકવો',
    voice_input: 'બોલીને કામ ઉમેરો',
    save: 'સાચવો',
    cancel: 'રદ કરો',
    delete: 'કાઢી નાખો',
    edit: 'સુધારો',
  },
  kn: {
    app_name: 'ಟಾಸ್ಕರ್',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    pending_tasks: 'ಬಾಕಿ ಕೆಲಸಗಳು',
    all_tasks: 'ಎಲ್ಲಾ ಕೆಲಸಗಳು',
    completed_tasks: 'ಪೂರ್ಣಗೊಂಡವು',
    bin: 'ಕಸದ ಬುಟ್ಟಿ',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    workspaces: 'ಕಾರ್ಯಕ್ಷೇತ್ರ',
    personal: 'ವೈಯಕ್ತಿಕ',
    family: 'ಕುಟುಂಬ ಮತ್ತು ಮನೆ',
    business: 'ವ್ಯವಹಾರ',
    finance: 'ಹಣಕಾಸು ಮತ್ತು ಬಿಲ್‌ಗಳು',
    vehicles: 'ವಾಹನಗಳು ಮತ್ತು PUC',
    documents: 'ದಾಖಲೆಗಳು',
    templates: 'ಪಟ್ಟಿಗಳು',
    reports: 'ವರದಿಗಳು',
    ask_ai: 'AI ಕೇಳಿ',
    add_task: 'ಕೆಲಸ ಸೇರಿಸಿ',
    search_placeholder: 'ಕೆಲಸಗಳು, ಬಿಲ್‌ಗಳನ್ನು ಹುಡುಕಿ...',
    streak_label: 'ದಿನಗಳ ಸರಣಿ',
    high_priority: 'ತುರ್ತು',
    due_today: 'ಇಂದಿನ ಗಡುವು',
    overdue: 'ಅವಧಿ ಮೀರಿದೆ',
    pay_now: 'UPI ಮೂಲಕ ಪಾವತಿಸಿ',
    voice_input: 'ಮಾತನಾಡಿ ಕೆಲಸ ಸೇರಿಸಿ',
    save: 'ಉಳಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    delete: 'ಅಳಿಸಿ',
    edit: 'ತಿದ್ದಿ',
  },
  ml: {
    app_name: 'ടാസ്കർ',
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    pending_tasks: 'തീർപ്പുകൽപ്പിക്കാത്തവ',
    all_tasks: 'എല്ലാ ജോലികളും',
    completed_tasks: 'പൂർത്തിയായവ',
    bin: 'ബിൻ',
    settings: 'ക്രമീകരണങ്ങൾ',
    workspaces: 'വർക്ക്‌സ്‌പെയ്‌സ്',
    personal: 'വ്യക്തിപരം',
    family: 'കുടുംബവും വീടും',
    business: 'ബിസിനസ്സ്',
    finance: 'ധനകാര്യം & ബില്ലുകൾ',
    vehicles: 'വാഹനങ്ങൾ & PUC',
    documents: 'രേഖകൾ',
    templates: 'ടെംപ്ലേറ്റുകൾ',
    reports: 'റിപ്പോർട്ടുകൾ',
    ask_ai: 'AI ചോദിക്കൂ',
    add_task: 'ജോലി ചേർക്കുക',
    search_placeholder: 'ജോലികൾ, ബില്ലുകൾ തിരയുക...',
    streak_label: 'ദിവസങ്ങളുടെ സ്ട്രീക്ക്',
    high_priority: 'അടിയന്തിരം',
    due_today: 'ഇന്നത്തെ കാലാവധി',
    overdue: 'കാലാവധി കഴിഞ്ഞു',
    pay_now: 'UPI വഴി പണം നൽകുക',
    voice_input: 'സംസാരിച്ച് ജോലി ചേർക്കുക',
    save: 'സംരക്ഷിക്കുക',
    cancel: 'റദ്ദാക്കുക',
    delete: 'ഇല്ലാതാക്കുക',
    edit: 'തിരുത്തുക',
  },
  pa: {
    app_name: 'ਟਾਸਕਰ',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    pending_tasks: 'ਬਕਾਇਆ ਕੰਮ',
    all_tasks: 'ਸਾਰੇ ਕੰਮ',
    completed_tasks: 'ਪੂਰੇ ਹੋਏ ਕੰਮ',
    bin: 'ਰੱਦੀ',
    settings: 'ਸੈਟਿੰਗਾਂ',
    workspaces: 'ਵਰਕਸਪੇਸ',
    personal: 'ਨਿੱਜੀ',
    family: 'ਪਰਿਵਾਰ ਅਤੇ ਘਰ',
    business: 'ਕਾਰੋਬਾਰ',
    finance: 'ਵਿੱਤ ਅਤੇ ਬਿੱਲ',
    vehicles: 'ਵਾਹਨ ਅਤੇ ਪੀਯੂਸੀ',
    documents: 'ਦਸਤਾਵੇਜ਼',
    templates: 'ਚੈੱਕਲਿਸਟਾਂ',
    reports: 'ਰਿਪੋਰਟਾਂ',
    ask_ai: 'AI ਨੂੰ ਪੁੱਛੋ',
    add_task: 'ਕੰਮ ਸ਼ਾਮਲ ਕਰੋ',
    search_placeholder: 'ਕੰਮ, ਬਿੱਲ ਖੋਜੋ...',
    streak_label: 'ਦਿਨਾਂ ਦੀ ਲੜੀ',
    high_priority: 'ਜ਼ਰੂਰੀ',
    due_today: 'ਅੱਜ ਨਿਪਟਾਉਣ ਵਾਲੇ',
    overdue: 'ਮਿਆਦ ਪੁੱਗ ਚੁੱਕੀ',
    pay_now: 'UPI ਰਾਹੀਂ ਭੁਗਤਾਨ ਕਰੋ',
    voice_input: 'ਬੋਲ ਕੇ ਕੰਮ ਜੋੜੋ',
    save: 'ਸੰਭਾਲੋ',
    cancel: 'ਰੱਦ ਕਰੋ',
    delete: 'ਮਿਟਾਓ',
    edit: 'ਸੋਧੋ',
  },
};

export const getAppLanguage = (): SupportedLanguage => {
  return 'en';
};

export const setAppLanguage = (_lang: SupportedLanguage): void => {
  localStorage.setItem(LOCALE_STORAGE_KEY, 'en');
  window.dispatchEvent(new CustomEvent('language-changed', { detail: { language: 'en' } }));
};

export const t = (key: string, lang?: SupportedLanguage): string => {
  const currentLang = lang || getAppLanguage();
  const dict = TRANSLATIONS[currentLang] || TRANSLATIONS['en'];
  return dict[key] || TRANSLATIONS['en'][key] || key;
};
